api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#        paths: ['%kernel.project_dir%/src/DataProvider']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 2 # Default value
#    formats:
#        jsonhal:
#            mime_types:
#                - application/hal+json
#                - application/json