fos_oauth_server:
  db_driver: orm       # Drivers available: orm, mongodb, or propel
  client_class:        App\Entity\Security\Client
  access_token_class:  App\Entity\Security\AccessToken
  refresh_token_class: App\Entity\Security\RefreshToken
  auth_code_class:     App\Entity\Security\AuthCode
  service:
    user_provider: fos_user.user_provider.username