# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json' }
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys