fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\Security\User
  service:
    mailer: 'fos_user.mailer.noop'
  from_email:
    address: "%env(resolve:MAILER_USER)%"
    sender_name: "%env(resolve:MAILER_USER)%"