# config/routes.yaml
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

oauth2:
  resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'