version: '3'
services:
    apache:
        build: apache
        container_name: sf4_apache
        ports:
            - 8080:80
        volumes:
            - ./config/vhosts:/etc/apache2/sites-enabled
            - ../back:/www
        depends_on:
            - php

    php:
        build: php
        container_name: sf4_php
        volumes:
            - ../back:/www

    vuejs:
        build:
            context: ./vuejs
            dockerfile: Dockerfile
            args:
                - YOUR_APP_WEB_HTTP_PORT=8080
        ports:
            - "80:8080"
            - "8000:8000"  # only needed if using vue-cli UI
        volumes:
            - ../front:/www
        stdin_open: true
        tty: true
        environment:
            # https://cli.vuejs.org/guide/mode-and-env.html#modes
            # development is used by vue-cli-service serve
            - NODE_ENV=development
            # one way for hot reloading ... see above for details
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=100
            - YOUR_APP_WEB_HTTP_PORT=8080
